[package]
name = "wg-vanity-key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
core_affinity = "0.8.1"
rand_core = "0.6.4"
rayon = "1.8.0"
x25519-dalek-fiat = "0.1.0"
